version: 2
jobs:
 build:
   machine:
    image: ubuntu-2004:current
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: |
          TAG="0.1.${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}" 
          docker build -t atishekk/devops_app:$TAG .
          docker push atishekk/devops_app:$TAG
          sudo curl https://cli-assets.heroku.com/install.sh | sh
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a devops-ai-hw web
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a devops-ai-hw web

